#! /bin/sh

### Aliases:
alias find-process="ps aux | grep"
alias z='zsh --login'
alias htop='sudo htop'
alias tmux-named='tmux new -s'

## Ruby Related
alias be='bundle exec'

## Linux Only
alias ubuntu-ver="lsb_release -a"
alias linux-distro="python -c 'import platform; print platform.dist()'"
alias ufw-logs="grep UFW /var/log/syslog"
alias ip-address="hostname --all-ip-addresses"
alias ip-address-full="ip addr show"
alias list-ports="sudo netstat -lptu"

#alias for list of users


# Adding Psswd to PostgresQL users
# $ sudo -u postgres psql postgres
# postgres=# \password postgres


## PostgrewQL Related
alias ppsql='sudo -u postgres psql'
alias pgu='sudo -u postgres'
alias pg_security_file='psql -c "SHOW hba_file;"'

## Python Related
alias django-admin='django-admin.py'
alias django-manage='python3 manage.py'


### Functions:

if (type dnf >/dev/null 2>&1 || exit 1 ); then
  alias yum2='dnf'
fi

# Pop OS login screen 
# (copies desktop resolution to login screen resolution)
funtion copy-to-gdm3-login-screen() {
  cp && sudo cp .config/monitors.xml /var/lib/gdm3/.config/ 
}